### ISSUE TITLE
Bundle an iOS version

### ISSUE THREAD

**Issue by guaka** [Trustroots/trustroots-expo-mobile#10]
Todo to get out a basic iOS app:

- [x] Fix "back to map" button in safari https://github.com/Trustroots/trustroots/issues/675
- [x] Fix `window.postMessage` #11  (I think it simply tells the site that we’re on webview and the site will then hide some stuff — I can check later how critical it is) 
- [x] Check that we have at least a home icon on iOS dash (some generated icons here: https://github.com/Trustroots/media/tree/master/icons/ios/native)
- [x] Get AppleId for Trustroots + developer account
- [x] Generate store certs, backup them, backup them again
- [ ] Maybe setup push notifications but don’t let it become a blocker
- [x] Send the app for review :tada:
- [ ] React to review feedback:
  - [x] Hide Google Play store badges on iOS https://github.com/Trustroots/trustroots/pull/1139
  - [ ] A mechanism for users to block abusive users https://github.com/Trustroots/trustroots/issues/1467
  - [ ] Update rules https://github.com/Trustroots/trustroots/issues/1468
- [ ] Re-send the app for review :tada:
- [ ] Send a newsletter to people who indicated they want to hear from us when the iOS app exists

**Comment by guaka** [comment]
https://developer.apple.com/enroll/

question: what account should I create: individual, self-corporate or trustroots foundation?

- with an organization account I can add users.
- didn't spot price difference yet

**Comment by simison** [comment]
Foundation please, so that we can have multiple users and avoid need of transferring the app later on (that can be hard / impossible, I didn't check).

**Comment by guaka** [comment]
https://expo.io/@trustroots/trustroots

"This project needs an update

This project uses Expo SDK v22.0.0. If you want to open this project, the author will need to update the project's SDK version."

**Comment by simison** [comment]
Since we have pretty minimal setup, updating to v22 or above might work just fine. Give it a try. :-)

**Comment by simison** [comment]
Expo has their clients for phones: https://expo.io/tools#client

...so in theory, just updating the SDK + running the CLI would give you something to test on a real device.

Testing on an emulator might be a little bit more work because you'd need to set all that up. I'm quite sure it's way easier than setting up an Android environment, though. :-D

**Comment by guaka** [comment]
todo now (@simison on slack)

(update: moved to issue description)

**Comment by simison** [comment]
I fixed issues in the `master` and submitted the app for review to Apple.

It bounced back with this change request:

> your app includes Google Play references in the home page.
>
>Referencing third-party platforms in your app or its metadata is not permitted on the App Store unless there is specific interactive functionality.

![image](https://user-images.githubusercontent.com/87168/64320808-f9543e00-cfc7-11e9-93f6-a7f095434ebb.png)

These app store badges don't make sense in mobile app context anyway so they should be all hidden when we're wrapping the app.

I've added [`?app` URL argument](https://github.com/Trustroots/trustroots-expo-mobile/blob/2a10e7ef3401e09371d1685de417c4cd18f25e8c/App.js#L56) when the app loads the website in the webview component, so we can in that scenario hide these things.

**Comment by simison** [comment]
Next steps:
- [x] hide store buttons when wrapping in webview https://github.com/Trustroots/trustroots/pull/1139
- [x] create Trustroots apple developer account (mikael)
- [ ] re-submit to apple for review (@simison @theo). I have the Apple dev account for Trustroots already.
- [ ] when accepted, update app store links to point to download page
- [ ] send email to people who asked to be notified when iOS app is out

**Comment by simison** [comment]
@guaka if you let me know your apple ID, I can add you to the Trustroots team in Apple dev center.

**Comment by simison** [comment]
I submitted a response to Apple about app store badge removed now and replied these questions that they asked:

> > To help us proceed with the review of your app, please review the following questions and provide as much detailed information as you can.
> 
> > - Does your app access any paid content or services?
> 
> It does not.
> 
> > - What are the paid content or services, and what are the costs?
> 
> No paid content nor services.
> 
> > - Do individual customers pay for the content or services?
> 
> No.
> 
> > - If no, does a company or organization pay for the content or services?
> 
> No.
> 
> > - Where do they pay, and what's the payment method?
> 
> No paid services.
> 
> > - If users create an account to use your app, are there fees involved?
> 
> No fees, the app is free of use.

**Comment by simison** [comment]
Next step:


> Upon further review, we found that your app does not comply with the following guidelines:
> 
> Guideline 1.2 - Safety - User Generated Content
> 
> Your app enables the display of user-generated content but does not have the proper precautions in place.
> 
> Next Steps
> 
> To resolve this issue, please revise your app to implement all of the following precautions:
> 
> - Require that users agree to terms (EULA) and these terms must make it clear that there is no tolerance for objectionable content or abusive users
> - A method for filtering objectionable content
> - A mechanism for users to flag objectionable content
> - A mechanism for users to block abusive users
> - The developer must act on objectionable content reports within 24 hours by removing the content and ejecting the user who provided the offending content
> 
> We look forward to reviewing your resubmitted app.
> 
> Best regards,
> 
> App Store Review

I think we can comply quite easily, just need to document them how we're doing it.

We don't have a feature to allow users to block each other, which would need to be developed. Shouldn't be too complicated though. Issue: https://github.com/Trustroots/trustroots/issues/1467

Clarifying rules/EULA here: https://github.com/Trustroots/trustroots/pull/1468

**Comment by sitarane** [comment]
Seems to mean that we're not sending a newsletter to the "I want an iPhone app" list.
Correct me if I'm wrong, otherwise, backburner.

**Comment by JohnvdWaeter** [comment]
Any progress on iOS?
